### ISSUE TITLE
[usb custom hid] giải thích giùm mình giá trị của biến

### ISSUE THREAD

**Issue by hieuhotxac** [hocarm/STM32F4-Discovery-Tutorial#1]
trong file usbd_custom_hid_if.c có cái biến:

__ALIGN_BEGIN static uint8_t CUSTOM_HID_ReportDesc_FS[USBD_CUSTOM_HID_REPORT_DESC_SIZE] __ALIGN_END =

{

	    /* USER CODE BEGIN 0 */ 

  0x06, 0x00, 0xFF,      // Usage Page = 0xFF00 (Vendor Defined Page 1)

  0x09, 0x01,             // Usage (Vendor Usage 1)

  0xA1, 0x01,             // Collection (Application)

  // Input report

  0x19, 0x01,             // Usage Minimum

  0x29, 0x40,             // Usage Maximum

  0x15, 0x00,             // Logical Minimum (data bytes in the report may have minimum value = 0x00)

  0x26, 0xFF, 0x00,       // Logical Maximum (data bytes in the report may have maximum value = 0x00FF = unsigned 255)

  0x75, 0x08,             // Report Size: 8-bit field size

  0x95, CUSTOM_HID_EPIN_SIZE,// Report Count

  0x81, 0x02,             // Input (Data, Array, Abs)

  // Output report

  0x19, 0x01,             // Usage Minimum

  0x29, 0x40,             // Usage Maximum

  0x75, 0x08,             // Report Size: 8-bit field size

  0x95, CUSTOM_HID_EPOUT_SIZE,// Report Count

  0x91, 0x02,             // Output (Data, Array, Abs)

  0xC0      

   

}; 

không biết là bạn tham chiếu từ đâu để có các số liệu này.

**Comment by hocarm** [comment]
Tool nha người anh em https://www.usb.org/document-library/hid-descriptor-tool
Bạn có thể tham khảo thêm http://www.usb.org/developers/hidpage/
